# Site Parameters 
theme: jekyll-theme-cayman
name: Drew Tatum
title: Drew Tatum
url: "https://drewtatum.github.io/"
page.title: Drew Tatum

# Navigation Bar
navbar-links:
  First Link: "First"
  Second Link: "Second"
 
